package version

var (
	// BuildTime is a time label of the moment when the binary was built
	BuildTime = "unset"
	// Commit is a last commit hash at the moment when the binary was built
	Commit = "unset"
	// Release is a semantic version of current build
	Release = "unset"
	// Name ...
	Name = "unset"
	// ProjectID ...
	ProjectID = "unset"
	// Version ...
	Version = "unset"
	// GoVersion ...
	GoVersion = "unset"
	// BuildDate ...
	BuildDate = "unset"
	// GitLog ...
	GitLog = "unset"
	// GitHash ...
	GitHash = "unset"
	// GitBranch ...
	GitBranch = "unset"
)
