version: '3.4'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluent/schema-registry:latest
    ports:
      - 8081:8081
    #volumes:
    #  - ./config/kafka/schema-registry.properties:/etc/schema-registry/schema-registry.properties
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka

  rest-proxy:
    image: confluent/rest-proxy:latest
    ports:
      - 8082:8082
    #volumes:
     # - ./config/kafka/kafka-rest.properties:/etc/kafka-rest/kafka-rest.properties
    links:
      - zookeeper
      - kafka
      - schema-registry
    depends_on:
      - zookeeper
      - kafka
      - schema-registry

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    environment:
      # yes localhost as its a client side app outsite of the docker network on your host
      - KAFKA_REST_PROXY_URL=http://rest-proxy:8082
      - PROXY=true
    ports:
      - 8000:8000
    links:
      - rest-proxy
    depends_on:
      - rest-proxy

  kafdrop:
    image: thomsch98/kafdrop
    environment:
      # yes localhost as its a client side app outsite of the docker network on your host
      - ZK_HOSTS=zookeeper:2181
      - LISTEN=9000
    ports:
      - 8001:9000
    links:
      - zookeeper
    depends_on:
      - zookeeper

  cli:
    image: taion809/kafka-cli:0.10.2.0
    command: kafka-topics.sh --list --zookeeper zookeeper:2181
    stdin_open: true
    tty: true
    links:
      - zookeeper
    depends_on:
      - zookeeper
