openapi: 3.0.1
info:
  title: Based on "Basic Auth Example"
  version: 1.0.0
  description: >
    An example for how to use Auth with Swagger.
    
servers:
  - url: '{protocol}://api.example.com'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https

paths:
  /signup:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: integer
                password:
                  type: string
              example:   # Sample object
                  email: test@tets.te
                  password: password123
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                example:   # Sample object
                  status: true
                  message: Please verify your email account using the confirmation code send to your mail
                  data: null

  /verify/mail:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: integer
                code:
                  type: string
              example:   # Sample object
                  email: test@tets.te
                  code: PatwtPil
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                example:   # Sample object
                  status: true
                  message: Mail Verification succeeded
                  data: null

  /reset-password:
    put:
      tags:
        - Auth
      requestBody:  
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                password:
                  type: string
                password_re:
                  type: string
                code:
                  type: string
              example:   # Sample object
                  password: test
                  password_re: test
                  code: PatwtPil
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                example:   # Sample object
                  status: true
                  message: Password Reset Successfully
                  data: null
  
  /verify/password-reset:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: integer
                code:
                  type: string
              example:   # Sample object
                  email: test@tets.te
                  code: PatwtPil
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      Code:
                        type: string
                example:   # Sample object
                  status: true
                  message: Password Reset code verification succeeded
                  data:
                    Code: fsfykSBG
  /login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: integer
                password:
                  type: string
              example:   # Sample object
                  email: test@tets.te
                  password: password123
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      refresh_token:
                        type: string
                      access_token:
                        type: string
                      username:
                        type: string
                example:   # Sample object
                  status: true
                  message: Successfully logged in
                  data:
                    refresh_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhY2MzMjFhNy00NDQ3LTRlY2MtYTI2Ni04MWE1ODVjYjE2ODMiLCJDdXN0b21LZXkiOiI4OTU4Zjc5ZWU3ZWY3ZmI3OTU2ZmNlMjRmOTNmN2EzZTJmY2M1Nzg0MTVlOTI5NDJmNDdjODlhYzQzNzNhNGZkIiwiS2V5VHlwZSI6InJlZnJlc2giLCJpc3MiOiJib29raXRlLmF1dGguc2VydmljZSJ9.dgmMslU1rk5voSsUHXac-9zTouc-O9bsLQVrbVg4Ye8O86lr_Z9AcdPZu2xGuSaPuRTxkHDCySk3mp_Wdh3TAQ7EcBeoG6V6ClUMasv5Zw
                    access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhY2MzMjFhNy00NDQ3LTRlY2MtYTI2Ni04MWE1ODVjYjE2ODMiLCJLZXlUeXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQ4NTQ4MDgwLCJpc3MiOiJib29raXRlLmF1dGguc2VydmljZSJ
                    username: none

  /refresh-token:
    get:
      tags:
        - Auth
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      refresh_token:
                        type: string
                      access_token:
                        type: string
                example:   # Sample object
                  status: true
                  message: Successfully generated new access token
                  data:
                    refresh_token:
                    access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJhY2MzMjFhNy00NDQ3LTRlY2MtYTI2Ni04MWE1ODVjYjE2ODMiLCJLZXlUeXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQ4NTQ4MDgwLCJpc3MiOiJib29raXRlLmF1dGguc2VydmljZSJ
      security:
        - bearerAuth: []
      


  /get-password-reset-code:
    get:
      tags:
        - Auth
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:      # Request body contents
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                example:   # Sample object
                  status: true
                  message: Please check your mail for password reset code
                  data: null
      security:
        - bearerAuth: []

  /profile:
    get:
      tags:
        - Auth
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - bearerAuth: []
        
        
        
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          nullable: true
          readOnly: true
        email:
          type: string
          nullable: true
          readOnly: true
        username:
          type: string
          nullable: true
          readOnly: true
        isverified:
          type: boolean
          nullable: true
          readOnly: true
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authorization header using the Bearer scheme.
      scheme: bearer
      bearerFormat: JWT
