package redis

var data = `{
    "general":{
       "bids_volume":500,
       "push_limit_per_token":10,
       "start_hour":9,
       "end_hour":22,
       "token_bid_interval":45
    },
    "campaigns":[
       {
          "id":8,
          "name":"UZEL site_id:7",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":100,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "UZEL"
                ]
             },
             {
                "field":"site_id",
                "operator":"IN",
                "values":[
                   "7"
                ]
             }
          ]
       },
       {
          "id":14,
          "name":"downmix",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "downmix"
                ]
             }
          ]
       },
       {
          "id":12,
          "name":"PUSH_AD",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "PUSH_AD"
                ]
             }
          ]
       },
       {
          "id":15,
          "name":"adxxx",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "adxxx"
                ]
             }
          ]
       },
       {
          "id":16,
          "name":"adnowgpay",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "adnowgpay"
                ]
             }
          ]
       },
       {
          "id":17,
          "name":"adnow",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "adnow"
                ]
             }
          ]
       },
       {
          "id":18,
          "name":"platinum",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "platinum"
                ]
             }
          ]
       },
       {
          "id":19,
          "name":"definishn",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":300,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "definishn"
                ]
             }
          ]
       },
       {
          "id":13,
          "name":"PUSHW",
          "dsp":{
             "id":3,
             "name":"proxy adnow + mgid",
             "bid_url":"http://exp-dsp.adnow-web.ru/dsp_proxy/",
             "active":true,
             "ext_fields":[
                "push_service",
                "offer_id",
                "site_id",
                "pw_gender",
                "time_zone",
                "goods_id",
                "template_name",
                "slave_prefix",
                "subacc",
                "subacc2",
                "preland_id",
                "s_trk",
                "package_prices",
                "old_price",
                "total_price",
                "price",
                "shipment_price",
                "sm_09",
                "sm_11",
                "sm_12",
                "sm_13",
                "sm_14",
                "sm_15",
                "reg_date",
                "age",
                "land_id",
                "device_type",
                "auth",
                "node",
                "iab_cat",
                "platform",
                "browser",
                "subtool",
                "safe_uid"
             ]
          },
          "subscriber_selection_size":1000,
          "targetings":[
             {
                "field":"node",
                "operator":"IN",
                "values":[
                   "PUSHW"
                ]
             },
             {
                "field":"subtool",
                "operator":"IN",
                "values":[
                   "fcm"
                ]
             }
          ]
       }
    ]
 }`
