apiVersion: v1
kind: Service
metadata:
  name: {{ include "boilerplate-go-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "boilerplate-go-chart.name" . }}
    helm.sh/chart: {{ include "boilerplate-go-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: {{ .Values.service.externalPortPrivate }}
    targetPort: {{ .Values.service.internalPortPrivate }}
    protocol: TCP
    name: {{ .Values.service.namePrivate }}
  selector:
    app.kubernetes.io/name: {{ include "boilerplate-go-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
